---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: admin-ui-ingress-admin-ui.local
  namespace: admin-ui
spec:
  hostnames:
    - admin-ui.local
    - sous-chef-proxy.local
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - backendRefs:
        - name: admin-ui-service
          port: 4000
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/admin-ui
status:
  parents: []
